### ISSUE TITLE
Kreiranje meta-modela

### ISSUE THREAD

**Issue by majak96** [majak96/dsl-project#4]
- [x] Kreirati meta-model na osnovu definisane gramatike. 

- [x] Implementirati dodatne provere uz pomoć object processor-a. 

- [x] Kreirati ugrađene objekte za predefinisane tipove pitanja.
